services:
  frontend:
    image: checkmate-frontend:latest
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - VITE_AUTH_ROOT=https://${DOMAIN}:${AUTH_PORT}
      - VITE_API_ROOT=https://${DOMAIN}:${API_PORT}
      - VITE_FRONTEND_PORT=${FRONTEND_PORT}
  auth-service:
    image: checkmate-auth-service
    ports:
      - ${AUTH_PORT}:9443
    volumes:
      - checkmate-db:/usr/share/checkmate:latest
    env_file: "auth.env"
    environment:
      - OZ_DATABASE_PATH=/usr/share/checkmate/tasks.db
      - FRONTEND_ROOT=http://${DOMAIN}:${FRONTEND_PORT}
  database-service:
    image: checkmate-database-service:latest
    ports:
      - ${API_PORT}:8443
    volumes:
      - checkmate-db:/usr/share/checkmate
    environment:
      - OZ_DATABASE_PATH=/usr/share/checkmate/tasks.db

volumes:
  checkmate-db: